#!/bin/bash

OPTION=$1
if [ "$OPTION" ]; then
        case "$OPTION" in
		rl)
			COMMAND="route:list"
			;;

		rlg)
			COMMAND="route:list | grep"
			;;
		mf)
			COMMAND="migrate:fresh"
			;;
		mfs)
			COMMAND="migrate:fresh --seed"
			;;
		mrfs)
			COMMAND="migrate:refresh --seed"
			;;
		*)
			COMMAND=$OPTION
			;;
	esac
fi
X="php artisan $COMMAND ${@:2}"
echo $X
$X
