#!/bin/bash
SITE_NAME=$1
if [ -z "$SITE_NAME" ]; then
	echo -e "\e[31mError : \e[39mMissing \"SITE_NAME\""
        echo -e "\e[32mSyntax : \e[39caws \"SITE_NAME\""
        exit
fi

if [ "$SITE_NAME" ]; then
	case "$SITE_NAME" in
		bee)
			SSH_URL="cbdeveloper@34.194.64.239"
			;;
		michmach)
			SSH_URL="${SSH_MICHMACH}"
			;;
		*)
			echo "No Site with this name is available..."
			exit
	esac
fi

echo $SSH_URL
ssh $SSH_URL

