#!/bin/bash
SITE_NAME=$1
if [ -z "$SITE_NAME" ]; then
	echo -e "\e[31mError : \e[39mMissing \"SITE_NAME\""
        echo -e "\e[32mSyntax : \e[39caws \"SITE_NAME\""
        exit
fi

if [ "$SITE_NAME" ]; then
	case "$SITE_NAME" in
		bee)
			SSH_URL="cbdeveloper@ec2-52-90-58-244.compute-1.amazonaws.com"
			;;
		*)
			echo "No Site with this name is available..."
			exit
	esac
fi

ssh $SSH_URL

